version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container-stury
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container-stury
    environment:
      PGADMIN_DEFAULT_EMAIL: gb@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "54321:80"
    depends_on:
      - postgres